# Generated by Django 3.1.1 on 2020-09-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karitato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(null=True),
        ),
    ]
