# Generated by Django 3.1.1 on 2020-09-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karitato', '0002_auto_20200922_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
