# Generated by Django 3.1.1 on 2020-09-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karitato', '0003_myuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
    ]
